[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#4A9EFF"
backgroundColor = "#1A1A1A"
secondaryBackgroundColor = "#2D2D2D"
textColor = "#FFFFFF" 